name: Compile

on:
  push:
    branches: [ "master" ]
    paths:
      - "gamemodes/**.pwn"
      - "gamemodes/**.inc"
      - "dependencies/**.inc"
      - ".github/workflows/compile.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "gamemodes/**.pwn"
      - "gamemodes/**.inc"
      - "dependencies/**.inc"
      - ".github/workflows/compile.yml"
  workflow_dispatch:
    inputs:
      name:
        required: false

jobs:
  compile:
    name: Pawn Compile
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
    env:
      OPTIONS: "-d3 -O0 -Z+ -C+ -t4" # -v2
      SOURCE_FILE: "test.pwn"
      SOURCES_PATH: "./gamemodes"
      AMX_PATH: "${{github.workspace}}/gamemodes/main.amx"
      INCLUDES_PATH: "${{github.workspace}}/dependencies"

    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        persist-credentials: false
        submodules: recursive
        fetch-depth: 0

    - name: Preparing some system related...
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y --fix-missing libc6:i386 libncurses6:i386 libstdc++6:i386 gcc-multilib g++-multilib
        sudo ln ./.github/pawncompiler/lib/libpawnc.so -s /usr/lib/libpawnc.so
        chmod +x ./.github/pawncompiler/bin/pawncc
        chmod +x ./.github/pawncompiler/bin/pawndisasm

    - name: Compiling
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        [[ -d ./.github/pawncompiler/bin ]] && echo "Directory './github/pawncompiler/bin' exists" || echo "Directory './github/pawncompiler/bin' doesn't exist"
        [[ -d ./.github/pawncompiler/lib ]] && echo "Directory './github/pawncompiler/lib' exists" || echo "Directory './github/pawncompiler/lib' doesn't exist"
        [[ -f ./.github/pawncompiler/bin/pawncc ]] && echo "File './github/pawncompiler/bin/pawncc' exists" || echo "File './github/pawncompiler/bin/pawncc' doesn't exist"
        [[ -f ./.github/pawncompiler/bin/pawndisasm ]] && echo "File './github/pawncompiler/bin/pawndisasm' exists" || echo "File './github/pawncompiler/bin/pawndisasm' doesn't exist"
        [[ -f ./.github/pawncompiler/lib/libpawnc.so ]] && echo "File './github/pawncompiler/lib/libpawnc.so' exists" || echo "File './github/pawncompiler/lib/libpawnc.so' doesn't exist"
        ./.github/pawncompiler/bin/pawncc "${{env.SOURCE_FILE}}" ${{env.OPTIONS}} -D"${{env.SOURCES_PATH}}" -o"${{env.AMX_PATH}}" -i"${{env.INCLUDES_PATH}}" -i"${{env.INCLUDES_PATH}}/openmultiplayer"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AMX
        path: "${{env.AMX_PATH}}"
        if-no-files-found: error