name: Compile

on:
  push:
    branches: [ "master","main" ]
    paths:
      - "gamemodes/**.pwn"
      - "gamemodes/**.inc"
      - "dependencies/**.inc"
      - ".github/workflows/compile.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "gamemodes/**.pwn"
      - "gamemodes/**.inc"
      - "dependencies/**.inc"
      - ".github/workflows/compile.yml"
  workflow_dispatch:
    inputs:
      name:
        required: false

jobs:
  compile:
    name: Pawn Compile
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
    env:
      OPTIONS: "-d3 -O0 -Z+ -C+ -t4" # -v2
      SOURCE_FILE: "main.pwn"
      SOURCES_PATH: "./gamemodes"
      AMX_PATH: "${{github.workspace}}/gamemodes/main.amx"
      INCLUDES_PATH: "${{github.workspace}}/dependencies"

    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        persist-credentials: false
        submodules: recursive
        fetch-depth: 0

    - name: Preparing some system related...
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y --fix-missing libc6:i386 libncurses6:i386 libstdc++6:i386 gcc-multilib g++-multilib gcc make cmake
        git clone https://github.com/openmultiplayer/compiler.git
        cd compiler
        mkdir build && cd build
        cmake ../source/compiler -DCMAKE_C_FLAGS="-m32 -O0 -g" -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
        make
    - name: Compiling
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        export LD_LIBRARY_PATH=./compiler/build/:$LD_LIBRARY_PATH
        ./compiler/build/pawncc ./gamemodes/main.pwn -o"${{env.AMX_PATH}}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AMX
        path: "${{env.AMX_PATH}}"
        if-no-files-found: error
